repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]
        types: [python]
        exclude: |
          (?x)^(
              \.eggs
            | \.git
            | \.hg
            | \.mypy_cache
            | \.tox
            | \.venv
            | _build
            | buck-out
            | build
            | dist
          )/

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        types: [python]
        exclude: |
          (?x)^(
              \.eggs
            | \.hg
            | \.mypy_cache
            | \.tox
            | \.venv
            | _build
            | buck-out
            | build
            | dist
          )/


  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python -m pytest --tb=short -q
        language: system
        pass_filenames: false
        always_run: true
        types: [python]
        stages: [pre-commit]
        verbose: true
        # Ne pas faire échouer le commit si les tests échouent
        require_serial: false


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: [--fix]
        types: [markdown]

  - repo: local
    hooks:
      - id: mdformat
        name: mdformat
        entry: mdformat
        language: system
        types: [markdown]
        args: [--wrap=88]
