agresso:
  prod: true
  sql-path: "sql"
  sql-filename-users: "get-agresso-n2f-users.prod.sql"
  sql-filename-customaxes: "get-agresso-n2f-customaxes.prod.sql"
n2f:
  base_urls: "https://www.n2f.com/services/api/v2/"
  simulate: false
  sandbox: false
