# Configuration de test pour les tests unitaires
database:
  host: "localhost"
  port: 1433
  database: "test_db"
  timeout: 30

api:
  base_url: "https://api.test.com"
  timeout: 30
  max_retries: 3

scopes:
  users:
    enabled: true
    display_name: "Users"
    sql_filename: "get-agresso-n2f-users.dev.sql"
    sql_column_filter: ["user_id", "username", "email"]
    sync_function: "business.process.user_synchronizer.UserSynchronizer.sync_users"

  axes:
    enabled: true
    display_name: "Custom Axes"
    sql_filename: "get-agresso-n2f-customaxes.dev.sql"
    sql_column_filter: ["axe_id", "axe_name", "axe_type"]
    sync_function: "business.process.axe_synchronizer.AxeSynchronizer.sync_axes"

cache:
  enabled: true
  persist_cache: false
  cache_dir: "cache"
  max_size_mb: 100
  default_ttl: 3600

memory_limit_mb: 1024
