"""
Constants and column names for business logic operations.
"""

# Fichier pour centraliser les constantes du projet, notamment les noms de colonnes.

# --- Noms de Colonnes Génériques ---
COL_CODE = "code"
COL_UUID = "uuid"
COL_NAMES = "names"
COL_CULTURE = "culture"
COL_VALUE = "value"

# --- Colonnes Agresso ---
AGRESSO_COL_EMAIL = "AdresseEmail"
AGRESSO_COL_MANAGER = "Manager"
AGRESSO_COL_COMPANY = "Entreprise"
AGRESSO_COL_AXE_TYPE = "typ"
AGRESSO_COL_AXE_CLIENT = "client"
AGRESSO_COL_FIRSTNAME = "Prenom"
AGRESSO_COL_LASTNAME = "Nom"
AGRESSO_COL_FUNCTION = "Fonction"
AGRESSO_COL_ROLE = "Role"
AGRESSO_COL_PROFILE = "Profil"
AGRESSO_COL_STRUCTURE = "Structure"
AGRESSO_COL_SSO_METHOD = "Methode_SSO"
AGRESSO_COL_LANGUAGE = "langue"
AGRESSO_COL_CURRENCY = "Devise"
AGRESSO_COL_EMPLOYEE_NUMBER = "Matricule"
AGRESSO_COL_COST_CENTER = "Centre_Cout"
AGRESSO_COL_CREATE_VEHICLE = "Creation_Vehicule"
AGRESSO_COL_APPROVE_VEHICLE = "Appro_Veh_Adm"
AGRESSO_COL_DEDUCT_DISTANCE = "Deduction_Distance_TravDom"
AGRESSO_COL_SSO_LOGIN = "Champs_Liaison_SSO"
AGRESSO_COL_PRO_PAYMENT = "Moyen_Paiement_Prof"
AGRESSO_COL_AUX_ACCOUNT = "Compte_Auxiliaire_Agresso"
AGRESSO_COL_AUX_ACCOUNT2 = "Compte_Auxiliaire2"
AGRESSO_COL_RAISE_LIMITS = "Droit_Relever_Plafond"
AGRESSO_COL_UPDATE_PERSONAL = "Update_Champs_Perso"
AGRESSO_COL_DESCRIPTION = "description"
AGRESSO_COL_DATE_FROM = "date_from"
AGRESSO_COL_DATE_TO = "date_to"
AGRESSO_COL_STATUS = "status"

# --- Colonnes N2F ---
N2F_COL_EMAIL = "mail"
N2F_COL_COMPANY_ID = "company_id"
N2F_COL_PROFILE = "profile"
N2F_COL_ROLE = "role"
N2F_COL_FIRSTNAME = "firstname"
N2F_COL_LASTNAME = "lastname"
N2F_COL_COMPANY = "company"
N2F_COL_MANAGER_MAIL = "managerMail"
N2F_COL_COST_CENTER = "defaultCostCenter"
N2F_COL_CREATE_VEHICLE = "canCreateVehicle"
N2F_COL_APPROVE_VEHICLE = "personnalCarHaveToBeApproved"
N2F_COL_DEDUCT_DISTANCE = "removeHomeWorkDistance"
N2F_COL_CULTURE = "culture"
N2F_COL_CURRENCY = "currencyIsoCode"
N2F_COL_JOB_TITLE = "jobTitle"
N2F_COL_EMPLOYEE_NUMBER = "employeeNumber"
N2F_COL_STRUCTURE = "structure"
N2F_COL_SSO_LOGIN = "ssoLogin"
N2F_COL_PRO_PAYMENT = "gotProPayment"
N2F_COL_AUX_ACCOUNT = "accountingAuxiliaryAccount"
N2F_COL_AUX_ACCOUNT2 = "accountingAuxiliaryNotReimbursableAccount"
N2F_COL_RAISE_LIMITS = "canRaiseLimits"
N2F_COL_AUTH_MODE = "authMode"
N2F_COL_UPDATE_PERSONAL = "canDefineHisAnalytics"
N2F_COL_VALIDITY_DATE_FROM = "validityDateFrom"
N2F_COL_VALIDITY_DATE_TO = "validityDateTo"

# --- Valeurs par défaut ---
DEFAULT_STRUCTURE = "L3"
DEFAULT_PROFILE = "Standard"
DEFAULT_ROLE = "Utilisateur"
DEFAULT_AUTH_MODE_SANDBOX = "Integrated"
DEFAULT_SSO_METHOD = "Sso"

# --- Cultures ---
CULTURE_FR = "fr"
CULTURE_NL = "nl"
